---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - kubebdp.github.io
  resources:
  - ServiceDefinitions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubebdp.github.io
  resources:
  - ServiceDefinitions/finalizers
  verbs:
  - update
- apiGroups:
  - kubebdp.github.io
  resources:
  - ServiceDefinitions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kubebdp.github.io
  resources:
  - clusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubebdp.github.io
  resources:
  - clusters/finalizers
  verbs:
  - update
- apiGroups:
  - kubebdp.github.io
  resources:
  - clusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kubebdp.github.io
  resources:
  - hdfses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubebdp.github.io
  resources:
  - hdfses/finalizers
  verbs:
  - update
- apiGroups:
  - kubebdp.github.io
  resources:
  - hdfses/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kubebdp.github.io
  resources:
  - stackdefinitions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubebdp.github.io
  resources:
  - stackdefinitions/finalizers
  verbs:
  - update
- apiGroups:
  - kubebdp.github.io
  resources:
  - stackdefinitions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kubebdp.github.io
  resources:
  - zookeepers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubebdp.github.io
  resources:
  - zookeepers/finalizers
  verbs:
  - update
- apiGroups:
  - kubebdp.github.io
  resources:
  - zookeepers/status
  verbs:
  - get
  - patch
  - update
