# permissions for end users to edit servicedefinitions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: servicedefinition-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubebdp
    app.kubernetes.io/part-of: kubebdp
    app.kubernetes.io/managed-by: kustomize
  name: servicedefinition-editor-role
rules:
- apiGroups:
  - kubebdp.github.io
  resources:
  - servicedefinitions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubebdp.github.io
  resources:
  - servicedefinitions/status
  verbs:
  - get
